### ISSUE TITLE
disable default tenants

### ISSUE THREAD

**Issue by rptete** [floragunncom/search-guard-module-kibana-multitenancy#1]
i would like we could disable global and private tenants for an user.

Very thanks.

**Comment by floragunn** [comment]
Thanks, we will add this feature in the final release.

**Comment by rptete** [comment]
You are welcome :)

**Comment by floragunn** [comment]
There are two situations that we need to keep in mind when implementing this:

1. Migration: At the moment, all stored objects created prior to installing the multi tenancy module are still available in the global tenant. If you disable it, you cannot access them anymore. This is probably a minor issue, and we just need to make people aware that previously created dashboards are not accessible anymore once you disable the global tenant.

2. Fallback: If you disable both the global and the private tenant, and there are no other tenants configured for the logged in user, we don't have any tenant to read/write to. So in our opinion it is mandatory to have at least one tenant as fallback, if no other tenants are available.

What's your opinion on these issues?

**Comment by rptete** [comment]
Hi!!

In my opinion the first case can be solved with a tool to edit indexes of kibana, and a configuration file that maps indices-tenants, so there would always be the index. (Although I like the current "automatic" option that hashes the user who first requests the tenant and creates the index with that hash).

And the second issue will be solved with that previous mapping, or, if you keep the automatic creation with the hash of the user, creating the index at the moment of the login, not when it is going to write in said index of kibana, and if user don’t have any tenant, the he could be added to global tenant.

In any case, i wouldn’t see positive the private tenant


Thanks you so much, great work!!

Un saludo,

**Comment by jochenkressin** [comment]
You can disable private and global tenant now. Upon login, we check whether the user that wants to log in has any configured tenant, since we need at least one as fallback. If no tenants are available, means global and private are disabled, and there are no other tenants configured, we display an error message.

**Comment by rptete** [comment]
That's perfect! 

Great work, guys :)

**Comment by floragunn** [comment]
Just released beta-3 which fixes this issue
