### ISSUE TITLE
"Private" tenant === "Global" tenant

### ISSUE THREAD

**Issue by hackery** [floragunncom/search-guard-module-kibana-multitenancy#13]
Search Guard version: 6.2.2-22.1
Platform: Windows 7 Pro SP1

I've been building some dashboards and visualizations to demonstrate the compartmentalization provided by the multitenancy feature, and found a persistent discrepancy that doesn't seem to fit the documentation or my expectations.

[Expected](https://docs.search-guard.com/latest/kibana-multi-tenancy.html#tenants-definition) (emphasis added):
> Any Kibana user always has access to two preconfigured tenants: Global and Private.
> 
> The Global tenant is shared with every user. This is the default tenant if no other tenant is selected. You’ll find objects that you have created before installing the multi tenancy module there.
> 
> The Private tenant **is not shared**. It is only accessible for the currently logged in user.

Observed: The **Private** tenant appears to hold the same objects as the **Global** tenant.

When I create a visualization or dashboard while logged in as Admin with the **Private** tenant selected, then switch to the **Global** tenant, I can still see the vis/dash. If I log in from another browser as a non-admin account, I can still see the dash/vis when selecting the **Global** tenant. The only way to create objects that are _actually_ private for the admin account are to use its **admin_tenant** tenant.

I see the same effect when creating in the **Global** tenant - objects are visible in the **Private** tenant.

Further, objects are visible across users. A visualization I create while logged in a non-admin account with their **Private** tenant selected, appears in **Global** for them, for Admin, and for a third non-admin user - and in their **Private** tenants.

There don't seem to be enough kibana indices in place to support **Private** tenants, unless there were some flag/acl in the main .kibana index, and I can't see one. `GET _cat/indices/.kib*` shows me
```
.kibana
.kibana_490181094_test1tenant
.kibana_826024361_test2tenant
.kibana_-152937574_admintenant
```
In the .kibana index I can see my Global and Private dashboards with nothing distinguishing them in terms of access.

**Comment by jochenkressin** [comment]
This looks like a bug with the private tenant in v12 of the Kibana plugin. This has already been fixed in v13. Can you please check the Kibana plugin version you are using?

**Comment by hackery** [comment]
Yup, looks like I'm a version behind on this cluster. (10 days - gotta move fast around here!)
Found [this thread](https://groups.google.com/forum/#!topic/search-guard/_Xa27dU_TQw) about it today, but looks like it didn't make it into a github issue.

Two questions though:
* Does the plugin report its version anywhere? (I can't see it, and had to diff against a fresh zip file) 
* Is there a release history somewhere for Search Guard that would have highlighted this? [Plugin Changelog](https://github.com/floragunncom/search-guard-kibana-plugin/wiki/Changelog) is stale; latest tag in github code is [v12](https://github.com/floragunncom/search-guard-kibana-plugin/tree/v6.2.2-12) and [releases list](https://github.com/floragunncom/search-guard-kibana-plugin/releases) doesn't show it.

**Comment by floragunn** [comment]
Links and tags have been corrected.
