### ISSUE TITLE
setting preferred tenant to private doesn't work

### ISSUE THREAD

**Issue by gevorg15** [floragunncom/search-guard-module-kibana-multitenancy#15]
I'm trying to set the preferred tenant when a user logs in to the Private tenant but its still defaulting to the Global tenant.  I have restricted access to the global tenant to only be RO so the user doesn't see the "management" menu item on the left when they initially log in. Even after switching tenants they have to refresh the page to see the management menu item.

I tried setting the preferred tenant via the kibana config using this option
```
"searchguard.multitenancy.tenants.preferred" => ["Private"],
```
but this doesn't seem to take affect and users are still defaulted to the Global tenant.  

I can disable the global tenant but I would prefer to leave it enabled so admins can create global visualizations, dashboards, searches, etc. for everyone else to consume if needed.

**Comment by floragunn** [comment]
I guess you need to type it lowercase
 `"searchguard.multitenancy.tenants.preferred" => ["private"],`
<hr>
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Comment by gevorg15** [comment]
Lowercase doesn't work either.  

I'm using kibana version 6.2.3 and elasticsearch version 6.2.3.  

Searchguard kibana plugin version 6.2.3-13 and searchguard version com.floragunn:search-guard-6:6.2.3-22.1

**Comment by jochenkressin** [comment]
Thanks for reporting, this is most likely a bug. We'll investigate.

**Comment by floragunn** [comment]
This was fixed in v14 of the Kibana plugin.
