### ISSUE TITLE
Selectively enable private tenant

### ISSUE THREAD

**Issue by marshall2day** [floragunncom/search-guard-module-kibana-multitenancy#16]
Hi,

Is it possible to only enable the private tenant for specific user groups? 

Thanks!

**Comment by floragunn** [comment]
Please do not ask questions here. 
For that refer to https://forum.search-guard.com or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
