### ISSUE TITLE
User hosted in a determinate tenant

### ISSUE THREAD

**Issue by rptete** [floragunncom/search-guard-module-kibana-multitenancy#2]
i would love that kibana automatically recognize the tenant associated with a certain user.
Without change it in the tenant tab (transparent to the user).

**Comment by floragunn** [comment]
a user could have more than one tenant

**Comment by rptete** [comment]
In that case, then, user switchs it manually in the "tenant" Tab.
But we could define the tenant by default for an user, not always Global Tenant.

**Comment by floragunn** [comment]
How about: Adding a "set as default" button on the tenants page. We would then store this as preference in a cookie, and read it when the user logs in next time. Or, simply store the last selected tenant in said cookie. What's your opinion?

**Comment by rptete** [comment]
I like this way, but if an user login for first time, what does tenant show first?

I meant to associate an user with an index of kibana (tenant) and that this association was hard and immutable. Although, still being multi tenant (I would like to have administrator users who were multitenant).
I think the best way is with an other file.yml in sgconfig, that uploaded this user-tenant mapping in the searchguard index

**Comment by floragunn** [comment]
Hm ... mapping tenants to users directly is probably not going to work well. If you have an external user directory as LDAP in place, you don't want to maintain a separate tenants.yml where you have to replicate all users you have in LDAP anyways. That's the main reason tenants are tied to Search Guard roles, not users.

If you would define a default tenant per role, then again, if a user is member of multiple roles, which tenant should be the default one?

**Comment by rptete** [comment]
mmmm... yes, you're right.
nah, the cookie is a good solution

**Comment by floragunn** [comment]
fixed with the newly released beta-3
