### ISSUE TITLE
Resize Tenant Tab when we collapsed left side menu

### ISSUE THREAD

**Issue by rptete** [floragunncom/search-guard-module-kibana-multitenancy#3]
![image](https://cloud.githubusercontent.com/assets/25149057/24287299/6eb81092-1079-11e7-90d5-5ed3192a15b9.png)
![image](https://cloud.githubusercontent.com/assets/25149057/24287313/791bed56-1079-11e7-83fe-72c2a81830c4.png)
![image](https://cloud.githubusercontent.com/assets/25149057/24287321/824b92be-1079-11e7-99e5-a6c7b26665e6.png)
![image](https://cloud.githubusercontent.com/assets/25149057/24287323/85540716-1079-11e7-967c-433f5711bb6e.png)

Thanks! :)

**Comment by floragunn** [comment]
Fixed with latest commit, will be released with beta3
