### ISSUE TITLE
Unexpected behavior (for me...)

### ISSUE THREAD

**Issue by rptete** [floragunncom/search-guard-module-kibana-multitenancy#4]
> cat /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_roles.yml
> ```
> rol_user_logan:
>   cluster:
>     - CLUSTER_USER
>   indices:
>     'logan*':
>       '*':
>         - READ
>     '?kibana':
>       '*':
>         - KIBANA_ACCESS
>   tenants:
>     logan: RW
> ```

> cat /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_action_groups.yml
> ```
> CLUSTER_USER:
>   - "cluster:monitor/*"
>   - "indices:data/read/mget"
>   - "indices:data/read/msearch"
>   - "indices:data/read/mtv"
>   - "indices:data/read/coordinate-msearch*"
>   - "indices:admin/aliases/exists*"
>   - "indices:admin/aliases/get*"
> ```
> ```
> KIBANA_ACCESS:
>   - "indices:data/read*"
>   - "indices:data/read/search"
>   - "indices:admin/mappings/fields/get*"
> ```

Why can "userLogan" create Index Patterns and Saved Objects?
How could we controlate that objects an user can create? (I need only dashboards, visualizations, etc)

**Comment by floragunn** [comment]
Index patterns are part of the saved objects, like Dashboards and Visualizations. We can only control access on an index level, means that if user logan has RW access to the logan tenant, he is able to create visualizations, dashboards etc. **and** can create index patterns. So, if the user has only read access as defined in the permissions for the kibana index, but has read/write access for the logan tenant, the latter overrides the first setting. 

What behaviour did you expect/want?

**Comment by rptete** [comment]
Yes, it's a nice way!

But, I think we need one tenant.yml in /sgconfig/ to determine this permissions more 'pro' xD
and in the moment to this file be upload to elasticsearch, the tenant is created
