### ISSUE TITLE
Not working when elasticsearch installed via rpm

### ISSUE THREAD

**Issue by AlexandrTuniev** [floragunncom/search-guard-module-kibana-multitenancy#5]
Hi, 
Thanks for great plugin!
I have installed elasticsearch 5.2.2 via rpm, then installed SG 5.2.2-11-mtbeta2 and copied jar for multitenancy  to plugin directory, but when started elasticsearch service in logs cant see  these lines 
```
***************************************************
Search Guard Kibana Multitenancy module is not free
software for commercial use in production.
You have to obtain a license if you 
use it in production.
***************************************************
Search Guard Kibana Multitenancy module is BETA
software, do not use it in production
***************************************************
```
and multi-tenancy doesn't works.
However when  I install and run elasticsearch from tar.gz extracted folder multi-tenancy works fine.

**Comment by floragunn** [comment]
What is "rmp"? Did you mean RPM?

**Comment by AlexandrTuniev** [comment]
Yes,  sorry  typo.

**Comment by floragunn** [comment]
How did you install the plugin?

**Comment by AlexandrTuniev** [comment]
as mentioned here https://github.com/floragunncom/search-guard-docs/blob/master/multitenancy.md
`elasticsearch-plugin install -b com.floragunn:search-guard-5:5.2.2-11-mtbeta2`

**Comment by floragunn** [comment]
This is pretty strange and sounds more like a elasticsearch bug

**Comment by floragunn** [comment]
Just for clarification, the lines in the log files:

```
***************************************************
Search Guard Kibana Multitenancy module is not free
software for commercial use in production.
You have to obtain a license if you 
use it in production.
***************************************************
Search Guard Kibana Multitenancy module is BETA
software, do not use it in production
***************************************************
```

are perfectly normal and simply mean that the multi tenancy module has been installed correctly. We'll remove the second part of this message once the official release is out.

**Comment by floragunn** [comment]
Seems that rpm and deb based installations will not redirect stdout into the logfile. This is not really a bug but we look into this. Its only about printing this statements, functionality is still there and module are loaded properly.

I close this issue here and will open another one in the search-guard repo pointing to this one.

Thx for reporting
