### ISSUE TITLE
Wrong version in Kibana config index/type when mixing versions

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-module-kibana-multitenancy#8]
I don't know if we should fix this, since it's recommended to always use a matching KI/ES version. This bug only occurs when mixing (compatible) versions:

Steps to reproduce:

- Install ES 5.3.2 with MT module
- Install KI 5.3.1 with SG plugin and MT enabled
- Set up a user with some demo tenants
- Log in to KI, choose a tenant other than Global
- Create an index pattern

Result:
A 404 is returned:
Config: Error 404 Not Found: [document_missing_exception] [config][5.3.1]: document missing, with { index_uuid="akOwNXaGQgacXiLgYeitPQ" & shard="0" & index=".kibana_1593390681_performancedata" }

Reason:
The document type "config" in the (rewritten) Kibana index contains a version number:

```
{
_index: ".kibana",
_type: "config",
_id: "5.3.2",
_score: 1,
_source: {
buildNum: 14849,
defaultIndex: "humanresources"
}
```
The version number must match the Kibana version, it seems it is included in the query that KI issues.

However, in the MT module, we always use the version of ES when creating the index, see com.floragunn.searchguard.configuration.PrivilegesInterceptorImpl, l. 154ff:

```
final SearchHit[] hits = response.getHits().getHits();
String id = null;
...                                                            
if (hits != null && hits.length > 0) {
  id = hits[0].getId();
  ...
  client.prepareIndex(newIndexName, "config")
        .setId(id)**.setSource(source)
        ...
```

This means that in the use case mentioned above KI queries the index with version 5.3.1, but we have created a document with id 5.3.2. This leads to the mentioned 404.

**Comment by floragunn** [comment]
Decision is to output an error message if the KI/ES versions do not match.

**Comment by floragunn** [comment]
tracked here https://github.com/floragunncom/search-guard-kibana-plugin/issues/26
