### ISSUE TITLE
Upgrading tenants fails

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-module-kibana-multitenancy#9]
Steps to reproduce:

- Install ES and KI 5.3.1, with full MT support 
- Log in with a user that has some tenants
- Choose the Global tenant
- Create an index pattern, a visualization etc.
- Choose a tenant other than Global
- Create an index pattern, a visualization etc.
- Upgrade ES and KI to 5.3.2
- Login again with the same user

Result: 
When accessing the Global tenant, everything works as expected. When trying to access data the non-Global tenant, 404s are returned.

Cause:
I'm not 100% sure yet about the sequence of calls from KI, but here are the findings so far:

When creating the indices with 5.3.1, both have one entry of type config with id 5.3.1:

```
{
 _index: ".kibana",
 _type: "config",
 _id: "5.3.1",
 _score: 1,
 _source: { 
   buildNum: 14844,
   defaultIndex: "humanresources"
}
```

After the upgrade to 5.3.2, the Global tenant has a second entry with version 5.3.2, and the same contents as the 5.3.1 one:

```
{
  _index: ".kibana",
  _type: "config",
  _id: "5.3.2",
  _score: 1,
  _source: {
    buildNum: 14849,
    defaultIndex: "humanresources"
  }
}
```

This entry is missing in all other tenants, leading to 404s. There seems to be a problem with the PrivilegesInterceptor when Kibana tries to copy over the entry, or creating it new. 

I will investigate the calls from KI during the upgrade process.

Might be related to #8

**Comment by floragunn** [comment]
Decision is to check (once for every tenant/tenant index) if the version bit as present, otherwise copy it over from and leave index pattern intact. Will be released with next version of MT module.

**Comment by floragunn** [comment]
Fixed with v2 release of this plugin
